### ISSUE TITLE
Mangas Not showing properly

### ISSUE THREAD

**Issue by aglibert393192** [enakada/foxy-manga-reader#1]
I move my comment from firefox's page to here, where it belongs :)
So my problem is, when trying to load mangas on mangafox, sometimes it doesn't load on the first page. Refreshing or moving to another page works perfectly fine :)

**Comment by enakada** [comment]
Let me see if I can understand what is happening. Sometimes, when you load a chapter it opens page 6, for example, and not the first page?

I can't seem to reproduce this issue locally, can you answer the following questions for me?

- Firefox version?
- Visualization mode? (infinite scrolling, dual, single)
- Does it only happen when you load a chapter from within the add-on popup?
- Can you post a link of a manga in which the problem happens?

**Comment by aglibert393192** [comment]
No, sometimes when I open a chapter, it opens page one and only that one.
I'm using firefox 57.0.3 , infinite scrolling mode , it was happening with
http://mangafox.la/manga/noblesse , but since the update I've got other
problems :D

2018-01-02 13:33 GMT+01:00 Edson Nakada <notifications@github.com>:

**Comment by enakada** [comment]
Well, I will keep an eye out for this problem anyway! Next version will have some improvements for broken images and page reload.

> but since the update I've got other problems

Feel free to open a new issue for these problems so I can fix them! :)
