### ISSUE TITLE
Error removing mangas

### ISSUE THREAD

**Issue by PedroMT** [enakada/foxy-manga-reader#10]
Hello, 

Ever since that problem with mangafox domain, I decided to migrate my mangas to other sites, but one thing I noticed is that I can't delete mangas from mangafox from the watchlist, it seems like if the extension can't find the manga page it returns an [error](https://puu.sh/zk2H0/27e950e006.png), instead of simply deleting from the bookmark list.

**Comment by enakada** [comment]
Hi there,

It seems to be a problem with the upgrade to v0.5.2. Probably, something was not renamed correctly during the upgrade. In order to release a fix during the weekend:

- Can you generate a backup of your bookmark list and post it here?
