### ISSUE TITLE
No images loading

### ISSUE THREAD

**Issue by kamte** [enakada/foxy-manga-reader#12]
For some reason, no image loads for any manga since yesterday. I've tried fanfox, kissmanga and mangahere, to no avail. I get a series of warnings for scripts failing to load in the console, don't know if it could be related:

![imagen](https://user-images.githubusercontent.com/6419046/36299636-3b329e1c-12fe-11e8-8299-216f35189d65.png)

**Comment by kamte** [comment]
Seems to have solved itself after 2 days. Closing the issue, but would love to discover what the cause was

**Comment by enakada** [comment]
Hi, there!

I'm sorry I took this long to reply, I had some problems last week. From what you explained this was a problem with the source. Did you try deactivating Foxy and reloading the page? 

> I get a series of warnings for scripts failing to load in the console, don't know if it could be related:

All these warnings are from the scripts running in these sources (no exception). All of them are trying to load ads to the page. Foxy's errors appear as `SOURCE_NAME.js` in the console, for example: `kissmanga.js`
