### ISSUE TITLE
Update notifications working erratically

### ISSUE THREAD

**Issue by kamte** [enakada/foxy-manga-reader#14]
Most of the time, notifications are not working. Either I don't get notified, or I get a random, big-ish number (around the hundreds). When clicking the extension's icon, most of the time I can't even see any updates in my list.

**Comment by enakada** [comment]
Hi there,

Sorry for the delay, can you tell me the error code that appears for you? I will check the notifications to see if I can find any problem.

**Comment by kamte** [comment]
I am not getting any errors. Upon further inspection, the number I get seems to match the total number of chapters the updated manga has, regardless of what chapters I've read.

My biggest issue right now has to do with not getting updated most of the times if a manga has new chapters; the number shown in the notification is a minor thing in comparison.

Here's a backup of my current manga list in hopes that it can be of help:
[backup.zip](https://github.com/enakada/foxy-manga-reader/files/1988047/backup.zip)

Thanks for replying!

**Comment by enakada** [comment]
Does it happen with a specific manga or source?

I found a problem with the kissmanga source, I think they changed their DDoS protection provider. Updates from this source will only work if you access the website first and let the browser solve the challenge and cache solution.

I'm working on a fix for that, but it might take time to find a workaround. Can you run `about:debugging` in your browser and open the debug window for Foxy? See if you can find `Error #302` being logged.

**Comment by enakada** [comment]
> I'm working on a fix for that, but it might take time to find a workaround.

The fix was easier than I thought so it will be applied in the next release (v0.7.0). Please tell me if you still have problems with the updates.

**Comment by kamte** [comment]
Sure! I will check as soon as I get the updated version.

Thanks for spending your time developing this great extension! :)

**Comment by kamte** [comment]
Everything seems to be working as it should!

Closing this issue :)
