### ISSUE TITLE
mangahere doesn't update again

### ISSUE THREAD

**Issue by DaoOfDarkness** [enakada/foxy-manga-reader#15]
Mangahere doesn't get updates

**Comment by enakada** [comment]
Hi there, just giving you an update. I will be looking into this problem during the weekend. Not yet sure what happened, but I think they changed their source code.

**Comment by enakada** [comment]
I couldn't find a problem with the code, I think the request was being cached by the browser, preventing chapter updates. I've added a random number to the end of the URL to see if this solves the problem. Please tell me if v0.7.3 fixes the problem for you.

**Comment by DaoOfDarkness** [comment]
at around on June 2018, 8:48 PM GMT+8, the plugin finally worked

tyvm for the hard work :D

    On Sunday, 10 June 2018, 8:38:34 AM GMT+8, Edson Nakada <notifications@github.com> wrote:  
 
 
I couldn't find a problem with the code, I think the request was being cached by the browser, preventing chapter updates. I've added a random number to the end of the URL to see if this solves the problem. Please tell me if v0.7.3 fixes the problem for you.
