### ISSUE TITLE
Kiss Manga Regex Fails on special characters

### ISSUE THREAD

**Issue by Isotab** [enakada/foxy-manga-reader#16]
When special characters are used in urls for kissmanga the regex check fails and the side menu is not loaded. Regex makes my head hurt but it appears it comes down to the use of \w- for matching between /Manga/ and ?id=. Special characters are encoded in urls using %## which falls outside the scope of either w or -. In a test it appears that just changing the regex to /(((?:http\w*:\/\/)*[\w.]*kissmanga\.\w{2,3}\/Manga\/([\w-%]+)\/)([\w-]+\?id=\d+))(?:#(\d+))*/ works but I have no idea if that would have unintended consequences so I did not just want to create a pull request.

For reference the original regex is:  /(((?:http\w*:\/\/)*[\w.]*kissmanga\.\w{2,3}\/Manga\/([\w-]+)\/)([\w-]+\?id=\d+))(?:#(\d+))*/

I have only tested this on kissmanga since I have yet to fully transfer my bookmark list to supported sites for this tracker, but I would imagine this would be a issue everywhere if you rely on \w-.

Urls to recreate issue.
Working: http://kissmanga.com/Manga/Kingdom/Vol-037-Ch-403--The-Queen-Mother-s-Goal?id=318685
Failing: http://kissmanga.com/Manga/Kingdom/Vol-037-Ch-404--L%C3%BCshi-Chunqiu?id=318686

**Comment by enakada** [comment]
Hi there,

Thanks for spotting that bug. I ended up changing `\w-` for `\S` which includes all symbols except whitespaces. From what I've seen, kissmanga seems to be the only source that uses special characters in the URL. In any case, if you do find a problem with the other ones, please tell me :)

 I will release a hotfix in a moment.
