### ISSUE TITLE
error #104

### ISSUE THREAD

**Issue by Leouch1** [enakada/foxy-manga-reader#17]
When I try add http://kissmanga.com/Manga/Skeleton-Soldier-Skeleton-Soldier-Couldn%E2%80%99t-Protect-the-Dungeon I got error:"can not find manga cover".

**Comment by enakada** [comment]
Hi there, this will be fixed on v0.7.4. There was a regex that I forgot to change when I worked on Issue #16.

**Comment by Leouch1** [comment]
it is working now, thx <3
