### ISSUE TITLE
Lost my manga

### ISSUE THREAD

**Issue by amartyads** [enakada/foxy-manga-reader#19]
I opened Firefox and I see all my added manga has disappeared, both in the flyout and in the dashboard. Is there any way of getting them back?

**Comment by amartyads** [comment]
Okay so, this had happened yesterday, and I had tried some things to make it work, but it didn't work. Now i made this post, and almost immediately after a popup for a new chapter came up, and all my manga is back.

**Comment by enakada** [comment]
I'm glad your list is back again! That is not an issue I have ever seen. Please tell me if it happens again. Also, I recommend keeping a backup of your list for cases like this.
