### ISSUE TITLE
Issues Faced with Foxy

### ISSUE THREAD

**Issue by Mentora** [enakada/foxy-manga-reader#2]
As per your request, I moved from the Firefox review :)
Below is the issue I've encountered so far on my side.

1. The menu that appears on the right side positions itself in the middle of the whole manga page (I use infinite scrolling mode). It does not scroll as I move downward.
2. I am unable to go to the next or previous page by using the arrow keys. I have to either manualy click on the buttons on the right menu or select the chapter from the page list.
3. I also get some pictures in the drop down menu that is empty.
4. The options button on the drop down menu previously took me to the option page in add-ons. Now it does nothing.

Since you are already looking into item 3 - TQ.
The manga's are all from mangafox.
When these issues occured I had the following blockers:

1. Adblock Plus - https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/
2. Popup Blocker - https://addons.mozilla.org/en-US/firefox/addon/poper-blocker-pop-up-blocker/
3. Ghostery - https://addons.mozilla.org/en-US/firefox/addon/ghostery/
4. uBlock Origin - https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/
5. Decentraleyes - https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/

**Comment by enakada** [comment]
Thanks for moving the issue to GitHub!!

I've been trying to reproduce these bugs, but I can't. Doesn't seem to be a conflict with any of the ad blockers you use. 

I have just released version 0.3.1 with a couple of bug fixes. Can you test it out and check if you can still reproduce these bugs?

> I am unable to go to the next or previous **page** by using the arrow keys. I have to either manualy click on the buttons on the right menu or select the chapter from the page list.

Since you use 'infinite scrolling mode', do you mean you are trying to change chapters using the arrow keys? (and not the page) If so, thats a new feature which I can include for the next release.

**Comment by Mentora** [comment]
With version 0.3.1, the pic in the drop down menu is now visible.

Yes, since I'm using infinite scrolling, I use the arrow key to move to the next chapter. This function is usable on any manga site but if I open the manga from Foxy, the arrow key does not work.

**Comment by Mentora** [comment]
I have found out what was causing the issue with item 1. 
I had an add-on called Zoom for Firefox - https://addons.mozilla.org/en-US/firefox/addon/zoom/. 
Disabling this add-on fixed the problem.

**Comment by enakada** [comment]
> Yes, since I'm using infinite scrolling, I use the arrow key to move to the next chapter. This function is usable on any manga site but if I open the manga from Foxy, the arrow key does not work.

I will add it as a new feature for the next version. I haven't mapped the keyboard yet, so it was probably a script from mangafox that was doing the transitions.

> I have found out what was causing the issue with item 1.
I had an add-on called Zoom for Firefox - https://addons.mozilla.org/en-US/firefox/addon/zoom/.
Disabling this add-on fixed the problem.

Thanks! I will take a look at Zoom and see if I can make them compatible!

What about problem #4, was it fixed for you?

**Comment by Mentora** [comment]
Looks like the option button also works fine now since I removed the Zoom add-on.

**Comment by enakada** [comment]
Ok, the problem with Zoom is a bit harder than I expected. The thing is, Zoom adds a `transform: scale()` property to the page body and CSS transform does not work well with `position: fixed` (what Foxy uses for positioning the navigation menu). I might have to do the positioning using Javascript for that to work.

I won't be able to implement a solution right away (I have some critical bugs to solve). So for now I will just inform users about this incompatibility.

**Comment by Mentora** [comment]
I agree with your plan. It's better to focus on improving Foxy rather than making it compatible with a minor add-on like Zoom. Anyway, I have removed Zoom as it also has some undesired effects with certain websites especially ones with a drop down box. Also it kinda clash with the built-in zoom function of Firefox.
