### ISSUE TITLE
Upgrading problems

### ISSUE THREAD

**Issue by aglibert393192** [enakada/foxy-manga-reader#3]
Hi,
After the upgrade, my mangas were not showing properly in the window opened by clicking on the fox. If I went to the manga page on mangafox, it showed that the manga was bookmarked by foxy manga reader.
Clicking on the "unbookmark" then again on the "bookmark" button got me an error : "Error while bookmarking this manga" or something like that.
I have Add Block Plus working simultaneously
I'm running firefox 57.0.4

**Comment by enakada** [comment]
Hi! Can you specify why the manga was not showing properly in the Foxy popup? What was happening?

Also, can you help me debugging your problem?
- Open the address `about:debugging` on firefox
- Select the `Enable add-on debugging` option
- Scroll down to Foxy and click on `Debug`
- Go to the manga which is triggering the error and try bookmarking it again
- Copy the content of the debug window to this issue.

I will be improving all error notifications in the future, so it is easier to debug. But for now thats the only way.

**Comment by aglibert393192** [comment]
It was not a manga, it was all mangas :) They all disappeared from the
window when I upgraded :(
Now it's working, a series of reboots got it working :-/ Should I still
paste the content ? Of which .js ?

2018-01-10 17:14 GMT+01:00 Edson Nakada <notifications@github.com>:

**Comment by enakada** [comment]
Sorry to hear that :( I haven't changed the upgrade process though. If you are not getting errors right now, the debug window will not help, sadly. For now, I recommend you keep a backup of your bookmarks. At least until v.1.0 is released.

I will check how to improve the upgrade process and I will be implementing some error codes. That way it will be much easier to debug if something happens again.

**Comment by enakada** [comment]
Commits f4c74f4602f0b42ae66126d54703ac5d4a6fef39 and 3f268d73ce8195168fc1308ab387001c7707dc60 improve the update process and also make errors easier to debug.
