### ISSUE TITLE
Bookmarks/Subscriptions not transferring across devices

### ISSUE THREAD

**Issue by magecu** [enakada/foxy-manga-reader#5]
Any idea why bookmarks are not transferring across devices ?
I have a windows notebook and a windows desktop.
The bookmarks set on the notebook and desktop do no sync.
Even when trying with a disconnected Firefox and removed foxy add-on , the bookmarks don't load when enabling firefox sync. The add-on is properly installed but the bookmarks don't transfer.

**Comment by enakada** [comment]
I found a problem with how Foxy initializes the sync storage. When Foxy is installed, it saves the bookmark structure to the sync storage (an empty list). The problem is that when data is synced, a conflict occurs and it keeps the current bookmark list (the empty one).

I will be releasing a hotfix for this issue sometime between the end of this week and the beginning of next week.

**Comment by magecu** [comment]
Wow, that was a quick response with the bug already identified. 
Thank you very much.

I have to say that even with the starting bugs, this is the best manga reader on either Firefox or Chrome.

**Comment by enakada** [comment]
The bug itself was easy to fix, but finding the source of it took some time. Mozilla should release a tool for debugging Firefox's sync storage. It would make developers' life much easier!

> I have to say that even with the starting bugs, this is the best manga reader on either Firefox or Chrome.

Thanks, I'm glad you like Foxy! I'm focusing on exterminating all these bugs now. The idea is to release a stable version (1.0.0) before March. Please, keep reporting any problems you find! That way we can make Foxy better much faster.

**Comment by magecu** [comment]
I have migrated all of my mangas to Foxy (somewhere between 300 and 400 completed and not completed). And I will be using it daily.
If I find anything else, I will let you know.

Thank you very much for your effort!

**Comment by enakada** [comment]
Hi, I just released the hotfix for the sync problem. Make sure you update the add-on (to v0.5.1) on both devices before trying to sync the list again. 

Also, you might have to disconnect/delete and reconnect your Firefox Sync Account for it to work (depends on the data that was saved to the account before the problem occurred). Make sure you have a backup of your list.

Feel free to reopen the issue if you still have any problem!

**Comment by magecu** [comment]
Follow up.

I was able to synchronize the foxy across two systems (both win 10).
There was only an issue with two mangas:
mangahere/devilchi
mangahere/81 diver

After manually removing and re-adding the two mangas everything seems to work as it should.

Thanks. :)
