### ISSUE TITLE
Multiple MangaHere Website

### ISSUE THREAD

**Issue by Mentora** [enakada/foxy-manga-reader#6]
Hi there.

I was testing the 3 supported sites and found that it did not work with MangaHere (https://manga-here.io/). Then I realise there is another website also called MangaHere (http://www.mangahere.cc/).

The proper link is found here in github but at the Firefox option's page only the name is given. My suggestion is to update the list by also including the URL address.

**Comment by enakada** [comment]
Hi Mentora!

Thanks for noticing that. I had no idea there were two MangaHere websites. I will update Firefox's information to include the URL address as well.
