### ISSUE TITLE
Problem with MangaFox

### ISSUE THREAD

**Issue by Mentora** [enakada/foxy-manga-reader#8]
Hi there.

I noticed that there is a problem with MangaFox. Any links of MangaFox is redirected to http://mangazoneapp.com/. I heard rumors that the owner has sold the domain but unable to verify. Even the link fanfox.net takes it to http://mangazoneapp.com/.

I've done my own search and so far am unable to discover the correct site.

**Comment by enakada** [comment]
Hi there,

This is from Mangafox [facebook page](https://www.facebook.com/mangafoxgo/posts/1549061391813647):

> #Notice #Jan31th2018
> Dear MangaFox's fans,
> 
> We have received feebacks from many users in Southeast Asia that they could not visit MangaFox and were redirected to MangaZone after MangaFox changed its domain into "fanfox.net" on Jan 30th,2018.
>
> At present, we prepared two solutions for our Southeast Asia fans who love read manga in MangaFox:
>
> 1)Visit fanfox.net on a VPN for other countries out of Southeast Asia.
> 2)Have a try with MangaZone.
> It is an free manga app where you can read all manga from MangaFox.Your bookmarks can also be exported to the app.
> 
> Sorry for the inconvenience! 🙇‍♀️🙇‍♂️
> We will keep improving the services of MangaFox.

Guess we have to wait for a bit until things stabilize on their end. I will be adding support to other 2 sources in the meanwhile.
